name = "dmg-collab-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[durable_objects]
bindings = [
  { name = "SESSION_ROOMS", class_name = "SessionRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SessionRoom"]
